name: Build and Deploy Script
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

steps:
  - uses: actions/checkout@v3
  - name: Use Node.js ${{ matrix.node-version }}
    uses: actions/setup-node@v3
    with:
      node-version: ${{ matrix.node-version }}
      cache: 'npm'
      cache-dependency-path: ./package-lock.json

  - name: Install Dependencies
    run: npm ci

  - name: Build Angular App
    run: npm run build --if-present

  - name: Test
    run: npm test

  - name: Deploy to GitHub Pages
    run: ng deploy --base-href=/portfolio/
    env:
      CLI: true
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
